export enum Field {
    Medicine = 1,
    Psychology = 2,
    Physics = 3,
    Chemistry = 4,
    Biology = 5,
    Science = 6,
    Books = 7,
    History = 8,
    Technology = 9,
    Art = 10,
    Animals = 11,
    Space = 12,
    Plants = 13,
    Music = 14,
    Sports = 15,
    Movies = 16,
    Games = 17,
    Food = 18,
    Fashion = 19,
    Crime = 20,
    Money = 21,
}
